/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package custom.componentes;

/**
 *
 * @author jairi
 */
public class DiaVisitas extends javax.swing.JPanel {

    private String dia = "dia";
    /**
     * Creates new form DiaVisitas
     */
    public DiaVisitas() {
        initComponents();
    }

    public String getDia() {
        return dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
        lblDia.setText(dia);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblDia = new javax.swing.JLabel();
        botonVisita3 = new custom.componentes.BotonVisita();
        botonVisita4 = new custom.componentes.BotonVisita();
        botonVisita5 = new custom.componentes.BotonVisita();
        botonVisita6 = new custom.componentes.BotonVisita();
        botonVisita7 = new custom.componentes.BotonVisita();
        botonVisita8 = new custom.componentes.BotonVisita();
        botonVisita9 = new custom.componentes.BotonVisita();
        botonVisita10 = new custom.componentes.BotonVisita();
        botonVisita11 = new custom.componentes.BotonVisita();

        jPanel1.setBackground(new java.awt.Color(204, 240, 243));

        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        botonVisita3.setText("10:00");
        botonVisita3.setEnabled(false);
        botonVisita3.setHora("10:00");
        botonVisita3.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita4.setHora("12:00");
        botonVisita4.setLabel("12:00");
        botonVisita4.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita5.setHora("13:00");
        botonVisita5.setLabel("13:00");
        botonVisita5.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita6.setHora("14:00");
        botonVisita6.setLabel("14:00");
        botonVisita6.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita7.setHora("15:00");
        botonVisita7.setLabel("15:00");
        botonVisita7.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita8.setHora("16:00");
        botonVisita8.setLabel("16:00");
        botonVisita8.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita9.setHora("17:00");
        botonVisita9.setLabel("17:00");
        botonVisita9.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita10.setHora("18:00");
        botonVisita10.setLabel("18:00");
        botonVisita10.setMaximumSize(new java.awt.Dimension(500, 27));

        botonVisita11.setHora("11:00");
        botonVisita11.setLabel("11:00");
        botonVisita11.setMaximumSize(new java.awt.Dimension(500, 27));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVisita4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
            .addComponent(botonVisita5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVisita11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVisita3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVisita11, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(botonVisita10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.componentes.BotonVisita botonVisita10;
    private custom.componentes.BotonVisita botonVisita11;
    private custom.componentes.BotonVisita botonVisita3;
    private custom.componentes.BotonVisita botonVisita4;
    private custom.componentes.BotonVisita botonVisita5;
    private custom.componentes.BotonVisita botonVisita6;
    private custom.componentes.BotonVisita botonVisita7;
    private custom.componentes.BotonVisita botonVisita8;
    private custom.componentes.BotonVisita botonVisita9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDia;
    // End of variables declaration//GEN-END:variables
}
